config/routes.rb
Rails.application.routes.draw do
  
 
  get 'order_items/create'
  get 'order_items/update'
  get 'order_items/destroy'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'home#index'

  resources :categories


  # delete 'orders/destroy/:id', to: 'orders#destroy', as: 'destroy_order'
  resources :products do
    resources :scores, except: [:show, :index]
  end
  
  resource :cart, only: [:show, :update] do
    member do
      post :pay_with_paypal
      get  :process_paypal_payment
    end
  end

  # post 'home/search' , as: 'home_search'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }


  # delete 'admin/categories/:id', to: 'admin/categories#destroy', as: 'destroy_categorty'
  authenticate :user do
    resources :addresses
    resources :order_items
    resources :order 
    resources :records
    end

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  # get '/auth/provider/callback', to: 'sessions#omniauth'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  require 'sendgrid-ruby'
  include SendGrid
  require 'json'

    def update
      product_id = params[:cart][:product_id]
      quantity = params[:cart][:quantity]
  
      current_order.add_product(product_id, quantity)
  
      redirect_to root_path, notice: "Product add to cart"
    end
  
    def show
      @products = Product.all
      @address = Address.all
      @order = current_order
      @order_items = @order.order_items
    end

  
    def destroy
      @order = current_order
      @order_item = @order.order_items.find(params[:id])
      @order_item.destroy
      @order_items = current_order.order_items
      redirect_to carts_path
    end

    def pay_with_paypal
    order = current_order
    price = order.total * 10

    response = EXPRESS_GATEWAY.setup_purchase(price,
      ip: request.remote_ip,
      return_url: process_paypal_payment_cart_url,
      cancel_return_url: root_url,
      allow_guest_checkout: true,
      currency: "USD"
    )

    payment_method = PaymentMethod.find_by(code: "PEC")
    Payment.create(
      order_id: order.id,
      payment_method_id: payment_method.id,
      state: "processing",
      total: order.total,
      token: response.token
    )

    redirect_to EXPRESS_GATEWAY.redirect_url_for(response.token)
  end



    def process_paypal_payment
      details = EXPRESS_GATEWAY.details_for(params[:token])
      express_purchase_options =
        {
          ip: request.remote_ip,
          token: params[:token],
          payer_id: details.payer_id,
          currency: "USD"
        }

      price = details.params["order_total"].to_d * 100

      response = EXPRESS_GATEWAY.purchase(price, express_purchase_options)
      if response.success?
        payment = Payment.find_by(token: response.token)
        order = payment.order

        #update object states
        payment.state = "completed"
        order.state = "completed"

        ActiveRecord::Base.transaction do
          order.save!
          payment.save!
        end
        
        #sendgrid 
        
        from = Email.new(email: 'johkcolom@gmail.com')
        subject = 'Hello World from the Twilio SendGrid Ruby Library'
        to = Email.new(email: 'johkcolom@gmail.com')
        content = Content.new(type: 'text/plain', value: 'Has comprado un producto electronico')
        mail = SendGrid::Mail.new(from, subject, to, content)
        # puts JSON.pretty_generate(mail.to_json)
        puts mail.to_json
      
        
        sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
        response = sg.client.mail._('send').post(request_body: mail.to_json)

        redirect_to root_path, notice: 'Compra exitosa'


      else
        redirect_to root_path, alert: 'Problemas con tu compra'
      end

    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.require(:cart).permit(:name, :photo, users_attributes: [:id,:user_id, :role, :address])
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<!--<div class="card">
    <div class="card-header bg-dark text-light">
        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
        <a href="<%= root_url%>" class="btn btn-outline-info btn-sm pull-right">Continue Shopping</a>
        <a  href="<%=addresses_path%>" class="btn btn-outline-info btn-sm pull-right" > Agregar direccion</a>
        <a  href="<%=records_path%>" class="btn btn-outline-info btn-sm pull-right" > Ver historial </a>

        <div class="clearfix"></div>
    </div>
    <div class="card-body">
      <% @order.order_items.includes(:product).each do |order_item| %>
        <div class="row row-card">
            <div class="col-xs-2 col-md-2">
                <%# <%= image_tag order_item.product.image.url(:thumb)%>
                <%= order_item.product.photo %>
            </div>
            <div class="col-xs-4 col-md-6">
              <h4 class="product-name"><strong><%= order_item.product.name %></strong></h4>
              <h4><small> <%= order_item.product.description %></small></h4>
            </div>
            <div class="col-xs-6 col-md-4 row">
                <div class="col-xs-6 col-md-6t" style="padding-top: 5px">
                  <h6><strong><%= order_item.price%> <span class="text-muted">x</span></strong></h6>
                </div>
                <div class="col-xs-4 col-md-4">
                  <%= order_item.quantity %>
                </div>
                <div class="col-xs-2 col-md-2">
                <%= @order.created_at%>
                </div>
            </div>
            <div>
              <%= link_to 'Destroy', order_item_path(order_item.id), remote: true, method: :delete, class: "btn btn-primary", data: { confirm: 'Are you sure?' } %>
            </div>
        </div>
        <% end %>

        <% if @order.order_items.present?  %>
          <div class="card-footer">
            <%= link_to 'Pagar', pay_with_paypal_cart_path, method: :post, class: 'btn btn-primary pull-rigth' %>
            <div class= 'pull-rigth' style= 'margin: 5px'>
              Total: $<b><%= @order.total %></b>
            </div>
            <% else %>
            <p>Tu carrito esta vacio</p>
            <% end %>
          </div>
            
        </div> -->

<div class="card">
  <div class="card-header bg-dark text-light">
      <i class="fa fa-shopping-cart" aria-hidden="true"></i>
      <a href="<%= root_url%>" class="btn btn-outline-info btn-sm pull-right">Continue Shopping</a>
      <a  href="<%=addresses_path%>" class="btn btn-outline-info btn-sm pull-right" > Agregar direccion</a>
      <a  href="<%=records_path%>" class="btn btn-outline-info btn-sm pull-right" > Ver historial </a>
  </div>
   <% @order.order_items.includes(:product).each do |order_item| %>
  <div class="container-card text-center">
      <div>
        <% if order_item.product.photo.attached? %>
            <%= image_tag order_item.product.photo, class:"imagen-home"%>
          <% end %>
          <div class="header-cart"><strong><%= order_item.product.name %></div>
          <div class="container-info">
            <div class="quantity"> <%=" Cantidad: #{order_item.quantity}" %></div>
            <div class="info-car">
              <div class="description"><%= order_item.product.description %></div>
              <div class="create"><%= @order.created_at%></div>
              <div><%= order_item.price%> x <%= order_item.quantity %></div>
            </div>
            <div class="btn-destroy">
              <%= link_to 'Eliminar', order_item_path(order_item.id), remote: true, method: :delete, class: "btn btn-primary  btn-search", data: { confirm: 'Are you sure?' } %>
            </div>
          </div>
      </div>
    </div>
    <% end %>
    <div>
       <% if @order.order_items.present?  %>
       <div>
        <div class= 'pull-rigth total' >
            Total: $<b><%= @order.total %></b>
          </div>
          <%= link_to 'Pagar', pay_with_paypal_cart_path, method: :post, class: 'btn btn-primary pull-rigth btn-pay' %>
            <% else %>
            <p>Tu carrito esta vacio</p>
            <% end %>
       </div>
    </div>
  </div>
</div>

app/views/carts/update.html.erb
<h1>Carts#update</h1>
<p>Find me in app/views/carts/update.html.erb</p>