config/routes.rb
Rails.application.routes.draw do
  
 
  get 'order_items/create'
  get 'order_items/update'
  get 'order_items/destroy'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'home#index'

  resources :categories


  # delete 'orders/destroy/:id', to: 'orders#destroy', as: 'destroy_order'
  resources :products do
    resources :scores, except: [:show, :index]
  end
  
  resource :cart, only: [:show, :update] do
    member do
      post :pay_with_paypal
      get  :process_paypal_payment
    end
  end

  # post 'home/search' , as: 'home_search'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }


  # delete 'admin/categories/:id', to: 'admin/categories#destroy', as: 'destroy_categorty'
  authenticate :user do
    resources :addresses
    resources :order_items
    resources :order 
    resources :records
    end

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  # get '/auth/provider/callback', to: 'sessions#omniauth'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
	has_one_attached :photo do |attachable|
		attachable.variant :thumb, resize: "100x100"
	end

validates :name, :photo, presence: true

# # Tiene un archivo adjunto llamado cover con dos versiones de tamaño
# has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" },
# :default_url => "/image/:thumb/missing.png"

# # Validación para evitar ataques y solo se suban los archivos de unas extensiones predefinidas
# validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/ 

has_and_belongs_to_many :products, dependent: :destroy



	def children
		Category.where(category_id: self.id)
	end

	def family
		family = []
		children1 = self.children
		children1.each do |c|
			family.push c
			x = c.children
			if x.count > 0
				family.push x
		end
		end
		family
	end

		def offspring(offsprings = nil)
			# ||=[] crea un arreglo vacio opcional
			offsprings ||= []
			childrens = Category.where(category_id: self.id)
			childrens.each do |child|
			offsprings << {id: child.id , name: child.name}
			child.offspring(offsprings)
			end
			offsprings
		end 
			# belongs_to :parent_category, class_name: "Category", optional: true, foreign_key: 'category_id', dependent: :destroy
			# has_many :children_categories, class_name: "Category", foreign_key: "category_id"

			# has_many :product_categories, dependent: :destroy
			# has_many :products, through: :product_categories

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # load_and_authorize_resource
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @category = Category.find(params[:id])
    @categories = Category.all
    # @products = Product.all
    @users = User.all
  end

  # GET /categories/1 or /categories/1.json
  def show
    @category = Category.find(params[:id])
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    # @product.destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :photo, users_attributes: [:id,:user_id, :role])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div id="category-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= @category.name %></h4>
      </div>
      <%= form_for @category, remote: true do |form| %>

        <div class="modal-body">
          <div class="form-group">
              <%= form.text_field :name, class: "form-control input-lg", placeholder: "Nombre Categoria" %>
          </div>    

          <div class="form-group">
            <%= form.file_field :photo, class: "form-control input-lg", placeholder: "Foto Categoria"  %>
          </div>
        </div>

        <div class="modal-footer">
          <%= form.submit class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/_index.html.erb
<h1 class="title-category">Categories</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <div class="container-category">
          <div class="circle-category">
            <div>
              <%= image_tag category.photo.url(:thumb)%>
            </div>
      
        </div>
            <div class="name-category"><%= link_to "#{category.name}", products_path %></div>
        <!--<div class="card" style="width: 18rem;">
          <img src="https://oscarsistemas.milaulas.com/pluginfile.php/2112/course/summary/ele.jpg" class="card-img-top" alt="...">
          <div class="card-body">
            <h2 class="card-title"><%= category.name %></h2>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>-->
        <% end %>
        <% @users.each do |user| %>
          <% if user == "moderador" %>
            <td><%= link_to 'Show', category %></td>
            <td><%= link_to 'Edit', edit_category_path(category) %></td>
            <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <%= link_to 'New Category', new_category_path %>
          <% end %>
        <% end %>
      </tr>
    
  </tbody>
</table>

app/views/categories/create.js.erb
<% if @category.errors.empty? %>

  $('table tbody').append(' <%= j render "row", category: @category %>');
  $('.alert-success').html("Categoria ha sido creada con éxito").show();
  $('#category-modal').modal('hide');
<% else %>

  alert('<%= @category.errors.full_messages[0] %>');
<% end %>

app/views/categories/edit.html.erb
<div class="container ">
    <h1 class= text-center>Editing Category</h1>

    <%= form_for @category, remote: true do |form| %>

        <div class="modal-body">
          <div class="form-group">
              <%= form.text_field :name, class: "form-control input-lg", placeholder: "Nombre Categoria" %>
          </div>    

          <div class="form-group">
            <%= form.file_field :photo, class: "form-control input-lg", placeholder: "Foto Categoria"  %>
          </div>
        </div>

        <div class="modal-footer">
          <%= form.submit class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>


</div>

app/views/categories/index.html.erb
<h1 class="title-category">Categories</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <div class="container-category">
          <div class="circle-category">
            <div>
              
            </div>
      
        </div>
            <div class="name-category"><%= link_to "#{category.name}", products_path %></div>
        <!--<div class="card" style="width: 18rem;">
          <img src="https://oscarsistemas.milaulas.com/pluginfile.php/2112/course/summary/ele.jpg" class="card-img-top" alt="...">
          <div class="card-body">
            <h2 class="card-title"><%= category.name %></h2>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>-->
        <% end %>
            <td><%= link_to 'Show', category %></td>
            <td><%= link_to 'Edit', edit_category_path(category) %></td>
            <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <%= link_to 'New Category', new_category_path, remote: true %>
      </tr>
    
  </tbody>
</table>

app/views/categories/new.js.erb
$('<%= j render "form", title: "Publicar Categoria" %>').modal();

app/views/categories/row.js.erb
<tr id="<%= category.id %>">
  <td><%= category.name %></td>
  <td><%= category.photo %></td>
  <td>
    <%= link_to "Editar", edit_product_path(category), remote: true %>
  </td>
</tr>

app/views/categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<figure class= "img-circle">
<% if @category.photo.attached? %>
  <%= image_tag(url_for(@category.photo))%>
  <% end %>
</figure>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', category_path(@category) %>