config/routes.rb
Rails.application.routes.draw do
  
 
  get 'order_items/create'
  get 'order_items/update'
  get 'order_items/destroy'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'home#index'

  resources :categories


  # delete 'orders/destroy/:id', to: 'orders#destroy', as: 'destroy_order'
  resources :products do
    resources :scores, except: [:show, :index]
  end
  
  resource :cart, only: [:show, :update] do
    member do
      post :pay_with_paypal
      get  :process_paypal_payment
    end
  end

  # post 'home/search' , as: 'home_search'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }


  # delete 'admin/categories/:id', to: 'admin/categories#destroy', as: 'destroy_categorty'
  authenticate :user do
    resources :addresses
    resources :order_items
    resources :order 
    resources :records
    end

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  # get '/auth/provider/callback', to: 'sessions#omniauth'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord

    has_one_attached :photo do |attachable|
		attachable.variant :thumb, resize: "100x100"
	end

    validates :name, :sku, :stock, :description, :price, :photo, presence: true

    has_and_belongs_to_many :categories
    belongs_to :user, optional: true
	has_many :scores
    has_many :order_items, dependent: :destroy
    has_many :orders, through: :order_items

	# Tiene un archivo adjunto llamado cover con dos versiones de tamaño
# has_attached_file :image, 
# styles: { medium: "300x300>", thumb: "100x100>" },
# :default_url => "/image/:thumb/missing.png"

# # Validación para evitar ataques y solo se suban los archivos de unas extensiones predefinidas
# validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/ 



end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # load_and_authorize_resource
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :set_category, only: %i[ index show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
    @users = User.all
    if params[:sku].present?
      @products = @products.where("sku ILIKE ?", "%#{params[:sku]}%")
    end
    # if params[:name].present?
    #   @categories = @categories.where("name = ?", params[:name])
    # end
  end

  # GET /products/1 or /products/1.json
  def show
    
    # @pagy, @scores = pagy(Score.all)
    @scores = Score.where(product_id: @product.id).order("created_at DESC")

    if @scores.blank?
      @average_score = 0
    else
      @average_score = @scores.average(:rating).round(2)
    end
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.create(product_params)
    # @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
      @users = User.all
    end

    def set_category
      @categories = Category.all
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :stock, :price, :photo, :sku,{category_ids: []}, categories_attributes: [:name], users_attributes: [:role, :ids])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div id="product-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= @product.name %></h4>
      </div>
      <%= form_for @product, remote: true do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <%= f.text_field :name, class: "form-control input-lg", placeholder: "Nombre del producto" %>
          </div>
          <div class="form-group">
            <%= f.file_field :photo, class: "form-control input-lg", placeholder: "Nombre del producto" %>
          </div>
          <div class="form-group">
            <%= f.number_field :stock, class: "form-control input-lg", placeholder: "Nombre del producto" %>
          </div>
          <div class="form-group">
            <%= f.text_area :description, class: "form-control input-lg", placeholder: "Nombre del producto" %>
          </div>
          <div class="form-group">
            <%= f.number_field :price, class: "form-control input-lg", placeholder: "Precio del producto" %>
          </div>
          <div class="form-group">
            <%= f.text_field :sku, class: "form-control input-lg", placeholder: "Precio del producto" %>
          </div>
          <div class="field">
            <%= f.collection_check_boxes(:category_ids,
                                        Category.all,
                                        :id,
                                        :name) do |b| %>
              <%= b.label class:"label-checkbox" do%>
              <%=b.check_box + b.text%>
              <%end%>
            <% end %>
          </div>
        <div class="modal-footer">
          <%= f.submit class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/create.js.erb
<% if @product.errors.empty? %>
  // add the row to the table, show alert and hide modal
  $('table tbody').append(' <%= j render "row", product: @product %>');
  $('.alert-success').html("El producto ha sido creado con éxito").show();
  $('#product-modal').modal('hide');
<% else %>
  // show first error
  alert('<%= @product.errors.full_messages[0] %>');
<% end %>

app/views/products/edit.html.erb
<h1 class= text-center>Editing Product</h1>
<div class="container">
<%= form_for @product, remote: true do |f| %>
			<div class="modal-body">
				<div class="form-group">
					<%= f.text_field :name, class: "form-control input-lg", placeholder: "Nombre del producto" %>
				</div>
				<div class="form-group">
					<%= f.file_field :photo, class: "form-control input-lg" %>
				</div>
				<div class="form-group">
					<%= f.number_field :stock, class: "form-control input-lg", placeholder: "Cantidad de stock" %>
				</div>
				<div class="form-group">
					<%= f.text_area :description, class: "form-control input-lg", placeholder: "Cararcteristicas" %>
				</div>
				<div class="form-group">
					<%= f.number_field :price, class: "form-control input-lg", placeholder: "Precio" %>
				</div>
				<div class="form-group">
					<%= f.text_field :sku, class: "form-control input-lg", placeholder: "Codigo" %>
				</div>
				<div class="field">
					<%= f.collection_check_boxes(:category_ids,
																			Category.all,
																			:id,
																			:name) do |b| %>
						<%= b.label class:"label-checkbox" do%>
						<%=b.check_box + b.text%>
						<%end%>
					<% end %>
				</div>
			<div class="modal-footer">
				<%= f.submit class: "btn btn-primary btn-lg btn-block" %>
			</div>
		<% end %>
	</div>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="container-product">
  <h1 class="title-product">Products</h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Category</th>
        <th>Stock</th>
        <th>Description</th>
        <th>price</th>
        <th>Sku</th>
        <th>Producto</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
          <% product.categories.each do |category| %>
        <tr>
            <td><%= product.name %></td>
            <td><%= category.name %></td>
            <td><%= product.stock %></td>
            <td><%= product.description %></td>
            <td><%= product.price %></td>
            <td><%= product.sku %></td>
            <td><%= link_to 'Ver Producto', product,  class: 'btn btn-primary pull-rigth btn-search'  %></td>
          <% if user_signed_in? && current_user.role =="moderador" %>
            <td><%= link_to 'Destroy', product, remote: true, method: :delete, data: { confirm: 'Are you sure?' },class: 'btn btn-primary pull-rigth btn-search' %></td>
          <% end %>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
                <% if user_signed_in? && current_user.role =="moderador"%>
                  <td><%= link_to 'New Product', new_product_path, remote: true, class: 'btn btn-primary pull-rigth btn-search' %> </td>
                <% end %>

  <br>
</div>

app/views/products/new.js.erb
$('<%= j render "form", title: "Crear Producto" %>').modal();

app/views/products/row.html.erb
<tr id="<%= product.id %>">
  <td><%= product.name %></td>
  <td><%= number_to_currency(product.price, precision: 2) %></td>
  <td>
    <%= link_to "Editar", edit_product_path(product), remote: true %>
  </td>
</tr>

app/views/products/show.html.erb
<div class="container-father"> 
  <div class='container-child'>
    <div class="container-imag-detail">
      <div>
        <% if @product.photo.attached? %>
          <%= image_tag @product.photo%>
        <% end %>
      </div>
    <div>
      <div class='title-product-show'>
          <h1><%= @product.name %> </h1>
      </div>
        <table class="table">
          <tbody>
            <tr>
              <td><strong>Stock:</strong></td>
              <td><%= @product.stock %></td>
            </tr>
            <tr>
              <td><strong>Descripción:</strong></td>
              <td><%= @product.description %></td>
            </tr>
            <tr>
              <td><strong>Precio:</strong></td>
              <td><%= @product.price %></td>
            </tr>
            <tr>
              <td><strong>Sku:</strong></td>
              <td><%= @product.sku %></td>
            </tr>
            <tr>
              <td><strong>Rating:</strong></td>
              <td>
                <div class="star-rating" data-score= <%= @average_score %> ></div>
                <em><%= "Promedio en base a #{@scores.length} calificaciones" %></em> 
              </td>
            </tr>
          </tbody>
        </table>
          <div>
            <%= form_for :cart, url: cart_path, method: :put do |f| %>
              <%= f.hidden_field :product_id, value: @product.id %>
              <%= f.hidden_field :quantity, value: 1 %>
              <%= f.submit "Add to cart", notice: "Agregado al carrito ",  class: 'btn btn-primary pull-rigth btn-search', style:"width:100%"%>
            <% end %>
        </div>
      </div>
    </div>
    <div>
      <% if @scores.blank? %>
        <h3 class="h3-title">Se el primero en calificar este producto</h3>
        <%= link_to "Califica", new_product_score_path(@product),  class: 'btn btn-primary pull-rigth btn-search' %>
      <% else %>
      <% if current_user %>
        <%= link_to "Vota por este producto", new_product_score_path(@product) %>
      <% end %>
      
        <% @scores.each do |score| %>
          <div class="reviews">
            <p>Usuario:<%=score.user_id%> </p>
            <div class="star-rating" data-score= <%= score.rating %> ></div>
            <div class="comentary">
            <%= score.comment %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>


<script>
      $('.star-rating').raty({
        path: '/assets/',
        readOnly: true,
        score: function() {
              return $(this).attr('data-score');
      }
    });
</script>

<td><% @users.each do |user| %>
  <% if user.role == "moderador"%>

  <% end %>
<% end %> 
</td>

  <% if user_signed_in? && current_user.role =="moderador"%>
    <td>
        <%= link_to 'Edit', edit_product_path(@product) %> |
        <%= link_to 'Back', products_path %> 
    </td>
  <% end %>